In [2]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import preprocessing
import os, sys
%load_ext autoreload
%autoreload 2

In [5]:
from lstm_rnn import (LSTMRNN, Hp, prepareData, get_batch, get_test_data,test,train)

In [7]:
x_train, y_train, x_test, y_test, standardized_xs,Hp = prepareData()

#train(x_train, y_train, standardized_xs, input_size=Hp.input_size, output_size=Hp.output_size,iter_num=200)
test(x_test, y_test)


seq.shape: (1920, 11)
result.shape: (1920, 1)
xs.shape: (1920, 1)
[[1367164800]
 [1367251200]
 [1367337600]
 ..., 
 [1534176000]
 [1534262400]
 [1534348800]]
[[  0.00000000e+00]
 [  9.92248062e-01]
 [  1.98449612e+00]
 ..., 
 [  1.91801550e+03]
 [  1.91900775e+03]
 [  1.92000000e+03]]


ValueError: Variable in_hidden/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)


In [8]:
y_test

array([[  2.08546293e-01],
       [ -1.21556289e-01],
       [ -2.11120424e-01],
       [ -4.22620361e-01],
       [ -7.50244889e-01],
       [ -2.82230143e-01],
       [ -3.72783735e-01],
       [ -3.43118362e-01],
       [ -3.77233665e-01],
       [  9.66629100e-02],
       [ -2.40939601e-01],
       [  1.52692825e-01],
       [  1.00180246e-01],
       [  1.17308084e-01],
       [ -1.62871128e-01],
       [ -5.49017722e-02],
       [ -2.61930612e-01],
       [ -2.64054870e-01],
       [ -1.68910097e-01],
       [ -4.67337847e-01],
       [ -4.23127483e-01],
       [ -3.90233811e-01],
       [ -3.00955608e-01],
       [ -2.70469152e-01],
       [ -1.28006720e-01],
       [ -5.39367457e-01],
       [ -8.30579350e-01],
       [ -1.48722982e+00],
       [ -1.19726589e+00],
       [ -1.06659475e+00],
       [ -1.11736499e+00],
       [ -9.71267110e-01],
       [ -8.85067047e-01],
       [ -5.52690025e-01],
       [ -3.69923108e-01],
       [  4.25280427e-01],
       [  1.23986576e-01],
 

In [8]:
with tf.Session() as sess:
    seq_test, res_test = get_test_data(x_test, y_test, Hp)
    test_predict = []
    for step in range(len(seq_test) - 1):
        prob = sess.run(model.pred, feed_dict={model.xs: seq_test[step]})
        predict = prob.reshape((-1))
        test_predict.extend(predict)
    res_test = np.array(res_test) 
    test_predict = np.array(test_predict) 
    acc = np.average(
        np.abs(test_predict - res_test[:len(test_predict)]) /
        res_test[:len(test_predict)])  #偏差
    #以折线图表示结果
    plt.figure()
    plt.plot(list(range(len(test_predict))), test_predict, color='b')
    plt.plot(list(range(len(res_test))), res_test, color='r')
    plt.show()

FailedPreconditionError: Attempting to use uninitialized value out_hidden/biases
	 [[Node: out_hidden/biases/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](out_hidden/biases)]]

Caused by op 'out_hidden/biases/read', defined at:
  File "C:\Program Files\Python35\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python35\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Program Files\Python35\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Program Files\Python35\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Program Files\Python35\lib\site-packages\tornado\platform\asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files\Python35\Lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Program Files\Python35\Lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "C:\Program Files\Python35\Lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Program Files\Python35\lib\site-packages\tornado\ioloop.py", line 760, in _run_callback
    ret = callback()
  File "C:\Program Files\Python35\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\zmq\eventloop\zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "C:\Program Files\Python35\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Program Files\Python35\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Program Files\Python35\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Program Files\Python35\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Program Files\Python35\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Program Files\Python35\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Program Files\Python35\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Program Files\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Program Files\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-ddf08a7905e2>", line 3, in <module>
    model = LSTMRNN()
  File "D:\JLCAI\insta360\myself\ML\angtk\xblong\lstm_rnn.py", line 132, in __init__
    self.add_output_layer()
  File "D:\JLCAI\insta360\myself\ML\angtk\xblong\lstm_rnn.py", line 182, in add_output_layer
    self.output_size,
  File "D:\JLCAI\insta360\myself\ML\angtk\xblong\lstm_rnn.py", line 218, in _bias_variable
    return tf.get_variable(name=name, shape=shape, initializer=initializer)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1328, in get_variable
    constraint=constraint)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1090, in get_variable
    constraint=constraint)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 435, in get_variable
    constraint=constraint)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 404, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 796, in _get_single_variable
    use_resource=use_resource)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2234, in variable
    use_resource=use_resource)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2224, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2207, in default_variable_creator
    constraint=constraint)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variables.py", line 259, in __init__
    constraint=constraint)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\variables.py", line 422, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 79, in identity
    return gen_array_ops.identity(input, name=name)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3887, in identity
    "Identity", input=input, name=name)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value out_hidden/biases
	 [[Node: out_hidden/biases/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](out_hidden/biases)]]


In [9]:
print(seq_test[0])

[[[-0.4148991  -0.41545929 -0.41197868 -0.41363626 -0.40966294  0.15770593
   -0.18258163  0.53748472 -0.50407503  0.01320152  0.20854629]
  [-0.4126464  -0.4153095  -0.43005166 -0.4244332  -0.40753202 -1.27863391
   -0.1252337  -0.5389013   1.17646532 -0.12524851 -0.12155629]
  [-0.42363084 -0.41975237 -0.42245108 -0.41681045 -0.41768462  0.84007283
   -0.15331702 -0.54615616 -0.68933819  0.00693129 -0.21112042]
  [-0.41608565 -0.41984564 -0.42339807 -0.4213794  -0.41064097 -0.5872143
   -0.17377999  0.01641026 -0.01838383  0.01173935 -0.42262036]
  [-0.42072026 -0.42382783 -0.42097353 -0.42184922 -0.41490801 -0.12046847
   -0.18445124  0.46690525 -0.56814992  0.03095266 -0.75024489]]]
